export const RESULTS_FETCH_STARTED = "RESULTS_FETCH_STARTED";
export const RESULTS_FETCH_SUCCESS = "RESULTS_FETCH_SUCCESS";
export const RESULTS_FETCH_FAILED = "RESULTS_FETCH_FAILED";

export const QUESTIONS_FETCH_STARTED = "QUESTIONS_FETCH_STARTED";
export const QUESTIONS_FETCH_SUCCESS = "QUESTIONS_FETCH_SUCCESS";
export const QUESTIONS_FETCH_FAILED = "QUESTIONS_FETCH_FAILED";

export const USERS_FETCH_STARTED = "USERS_FETCH_STARTED";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";

export const USER_LOGIN_STARTED = "USER_LOGIN_STARTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_TOKEN_VERIFY_START = "USER_TOKEN_VERIFY_START";
export const USER_TOKEN_SET = "USER_TOKEN_SET";
export const USER_TOKEN_VERIFY_COMPLETE = "USER_TOKEN_VERIFY_COMPLETE";

export const CHANGE_TAB = "CHANGE_TAB";



