export const RESULTS_FETCH_STARTED = "RESULTS_FETCH_STARTED";
export const RESULTS_FETCH_SUCCESS = "RESULTS_FETCH_SUCCESS";
export const RESULTS_FETCH_FAILED = "RESULTS_FETCH_FAILED";
export const USERS_FETCH_STARTED = "USERS_FETCH_STARTED";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";
export const TOKEN_SET = "TOKEN_SET";
export const TOKEN_INVALIDATE = "TOKEN_INVALIDATE";



